"""add_model_user

Revision ID: 60737cc0f346
Revises: f70de72c56b0
Create Date: 2023-05-16 15:19:05.813336

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '60737cc0f346'
down_revision = 'f70de72c56b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('email', sa.String(length=128), nullable=False),
                    sa.Column('hashed_password', sa.String(
                        length=128), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
