"""add_file_model

Revision ID: 68fb8e43e89e
Revises: 60737cc0f346
Create Date: 2023-05-16 18:46:30.694597

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '68fb8e43e89e'
down_revision = '60737cc0f346'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_file',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user', sa.UUID(), nullable=True),
                    sa.Column('filename', sa.String(
                        length=64), nullable=False),
                    sa.Column('file_path', sa.String(
                        length=64), nullable=False),
                    sa.Column('data', sa.LargeBinary(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('file_path'),
                    sa.UniqueConstraint('filename')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_file')
    # ### end Alembic commands ###
